create table if not exists public.video_learning_artifacts (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  user_id bigint not null references public.profiles(id) on delete cascade,
  lesson_id bigint not null references public.course_lesson(id) on delete cascade,
  course_id bigint references public.course(id) on delete set null,
  artifact_type text not null check (artifact_type in ('note', 'mind_map', 'quiz')),
  title text not null,
  content jsonb not null default '{}'::jsonb,
  source_timestamp_sec integer,
  generation_status text not null default 'completed'
    check (generation_status in ('queued', 'generating', 'completed', 'failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists video_learning_artifacts_user_lesson_idx
  on public.video_learning_artifacts (user_id, lesson_id, created_at desc)
  where deleted_at is null;

alter table public.video_learning_artifacts enable row level security;

create policy "Users can read their own video learning artifacts"
  on public.video_learning_artifacts for select
  to authenticated
  using (exists (
    select 1 from public.profiles
    where profiles.id = video_learning_artifacts.user_id
      and profiles.user_id = (select auth.uid())
  ));

create policy "Users can create their own video learning artifacts"
  on public.video_learning_artifacts for insert
  to authenticated
  with check (exists (
    select 1 from public.profiles
    where profiles.id = video_learning_artifacts.user_id
      and profiles.user_id = (select auth.uid())
  ));

create policy "Users can update their own video learning artifacts"
  on public.video_learning_artifacts for update
  to authenticated
  using (exists (
    select 1 from public.profiles
    where profiles.id = video_learning_artifacts.user_id
      and profiles.user_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.profiles
    where profiles.id = video_learning_artifacts.user_id
      and profiles.user_id = (select auth.uid())
  ));

create policy "Users can delete their own video learning artifacts"
  on public.video_learning_artifacts for delete
  to authenticated
  using (exists (
    select 1 from public.profiles
    where profiles.id = video_learning_artifacts.user_id
      and profiles.user_id = (select auth.uid())
  ));

grant select, insert, update, delete on public.video_learning_artifacts to authenticated;
grant usage, select on sequence public.video_learning_artifacts_id_seq to authenticated;
